# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fmcw_gui.ui'
#
# Created: Tue Jul 28 18:30:25 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 749)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setSizeIncrement(QtCore.QSize(2, 2))
        MainWindow.setBaseSize(QtCore.QSize(810, 780))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(640, 42, 121, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioTrigCont = QtGui.QRadioButton(self.groupBox)
        self.radioTrigCont.setGeometry(QtCore.QRect(0, 20, 116, 22))
        self.radioTrigCont.setChecked(False)
        self.radioTrigCont.setObjectName("radioTrigCont")
        self.radioTrigSingle = QtGui.QRadioButton(self.groupBox)
        self.radioTrigSingle.setGeometry(QtCore.QRect(0, 40, 116, 22))
        self.radioTrigSingle.setChecked(True)
        self.radioTrigSingle.setObjectName("radioTrigSingle")
        self.pushButtonTrigger = QtGui.QPushButton(self.centralwidget)
        self.pushButtonTrigger.setGeometry(QtCore.QRect(640, 10, 85, 27))
        self.pushButtonTrigger.setMaximumSize(QtCore.QSize(395, 16777215))
        self.pushButtonTrigger.setObjectName("pushButtonTrigger")
        self.rfpowerBox = QtGui.QCheckBox(self.centralwidget)
        self.rfpowerBox.setGeometry(QtCore.QRect(640, 110, 97, 22))
        self.rfpowerBox.setObjectName("rfpowerBox")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(630, 130, 171, 121))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 5, 66, 17))
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 30, 66, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 66, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 66, 17))
        self.label_3.setObjectName("label_3")
        self.startSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.startSpinBox.setGeometry(QtCore.QRect(60, 25, 63, 27))
        self.startSpinBox.setDecimals(3)
        self.startSpinBox.setSingleStep(0.1)
        self.startSpinBox.setProperty("value", 5.5)
        self.startSpinBox.setObjectName("startSpinBox")
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(130, 30, 31, 17))
        self.label_5.setObjectName("label_5")
        self.stopSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.stopSpinBox.setGeometry(QtCore.QRect(60, 55, 64, 27))
        self.stopSpinBox.setDecimals(3)
        self.stopSpinBox.setSingleStep(0.1)
        self.stopSpinBox.setProperty("value", 6.0)
        self.stopSpinBox.setObjectName("stopSpinBox")
        self.lengthSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.lengthSpinBox.setGeometry(QtCore.QRect(60, 85, 64, 27))
        self.lengthSpinBox.setDecimals(3)
        self.lengthSpinBox.setSingleStep(0.1)
        self.lengthSpinBox.setProperty("value", 1.0)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(130, 60, 31, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(130, 90, 21, 17))
        self.label_7.setObjectName("label_7")
        self.rangeplotW = PlotWidget(self.centralwidget)
        self.rangeplotW.setGeometry(QtCore.QRect(0, 0, 621, 511))
        self.rangeplotW.setObjectName("rangeplotW")
        self.timeplotW = PlotWidget(self.centralwidget)
        self.timeplotW.setGeometry(QtCore.QRect(0, 520, 621, 181))
        self.timeplotW.setObjectName("timeplotW")
        self.plotGroup = QtGui.QGroupBox(self.centralwidget)
        self.plotGroup.setGeometry(QtCore.QRect(630, 520, 120, 101))
        self.plotGroup.setObjectName("plotGroup")
        self.radioButton_time = QtGui.QRadioButton(self.plotGroup)
        self.radioButton_time.setGeometry(QtCore.QRect(0, 30, 116, 22))
        self.radioButton_time.setChecked(True)
        self.radioButton_time.setObjectName("radioButton_time")
        self.radioButton_range = QtGui.QRadioButton(self.plotGroup)
        self.radioButton_range.setGeometry(QtCore.QRect(0, 50, 116, 22))
        self.radioButton_range.setObjectName("radioButton_range")
        self.radioButton_none = QtGui.QRadioButton(self.plotGroup)
        self.radioButton_none.setGeometry(QtCore.QRect(0, 70, 116, 22))
        self.radioButton_none.setObjectName("radioButton_none")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Triggering", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTrigCont.setText(QtGui.QApplication.translate("MainWindow", "Continous", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTrigSingle.setText(QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTrigger.setText(QtGui.QApplication.translate("MainWindow", "Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.rfpowerBox.setText(QtGui.QApplication.translate("MainWindow", "RF power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.plotGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_time.setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_range.setText(QtGui.QApplication.translate("MainWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_none.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
