# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fmcw_gui.ui'
#
# Created: Sat Aug 22 19:35:51 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 750)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setSizeIncrement(QtCore.QSize(2, 2))
        MainWindow.setBaseSize(QtCore.QSize(810, 780))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(180, 120))
        self.frame_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 5, 66, 17))
        self.label_4.setObjectName("label_4")
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 30, 66, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 66, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 66, 17))
        self.label_3.setObjectName("label_3")
        self.startSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.startSpinBox.setGeometry(QtCore.QRect(60, 25, 63, 27))
        self.startSpinBox.setDecimals(3)
        self.startSpinBox.setSingleStep(0.1)
        self.startSpinBox.setProperty("value", 5.5)
        self.startSpinBox.setObjectName("startSpinBox")
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(130, 30, 31, 17))
        self.label_5.setObjectName("label_5")
        self.stopSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.stopSpinBox.setGeometry(QtCore.QRect(60, 55, 64, 27))
        self.stopSpinBox.setDecimals(3)
        self.stopSpinBox.setSingleStep(0.1)
        self.stopSpinBox.setProperty("value", 5.7)
        self.stopSpinBox.setObjectName("stopSpinBox")
        self.lengthSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.lengthSpinBox.setGeometry(QtCore.QRect(60, 85, 64, 27))
        self.lengthSpinBox.setDecimals(3)
        self.lengthSpinBox.setSingleStep(0.1)
        self.lengthSpinBox.setProperty("value", 0.5)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(130, 60, 31, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(130, 90, 21, 17))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.frame_3, 4, 1, 1, 1)
        self.timeplotW = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeplotW.sizePolicy().hasHeightForWidth())
        self.timeplotW.setSizePolicy(sizePolicy)
        self.timeplotW.setMinimumSize(QtCore.QSize(500, 100))
        self.timeplotW.setObjectName("timeplotW")
        self.gridLayout.addWidget(self.timeplotW, 7, 0, 1, 1)
        self.rangeplotW = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeplotW.sizePolicy().hasHeightForWidth())
        self.rangeplotW.setSizePolicy(sizePolicy)
        self.rangeplotW.setMinimumSize(QtCore.QSize(500, 400))
        self.rangeplotW.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rangeplotW.setObjectName("rangeplotW")
        self.gridLayout.addWidget(self.rangeplotW, 0, 0, 7, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setObjectName("groupBox")
        self.radioTrigCont = QtGui.QRadioButton(self.groupBox)
        self.radioTrigCont.setGeometry(QtCore.QRect(0, 20, 116, 22))
        self.radioTrigCont.setChecked(False)
        self.radioTrigCont.setObjectName("radioTrigCont")
        self.radioTrigSingle = QtGui.QRadioButton(self.groupBox)
        self.radioTrigSingle.setGeometry(QtCore.QRect(0, 40, 116, 22))
        self.radioTrigSingle.setChecked(True)
        self.radioTrigSingle.setObjectName("radioTrigSingle")
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_bigrange = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_bigrange.setGeometry(QtCore.QRect(0, 30, 116, 22))
        self.radioButton_bigrange.setChecked(True)
        self.radioButton_bigrange.setObjectName("radioButton_bigrange")
        self.radioButton_bigwaterfall = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_bigwaterfall.setGeometry(QtCore.QRect(0, 50, 116, 22))
        self.radioButton_bigwaterfall.setObjectName("radioButton_bigwaterfall")
        self.gridLayout.addWidget(self.groupBox_2, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.rfpowerBox = QtGui.QCheckBox(self.centralwidget)
        self.rfpowerBox.setObjectName("rfpowerBox")
        self.gridLayout.addWidget(self.rfpowerBox, 2, 1, 1, 1)
        self.pushButtonTrigger = QtGui.QPushButton(self.centralwidget)
        self.pushButtonTrigger.setMaximumSize(QtCore.QSize(395, 16777215))
        self.pushButtonTrigger.setObjectName("pushButtonTrigger")
        self.gridLayout.addWidget(self.pushButtonTrigger, 0, 1, 1, 1)
        self.plotGroup = QtGui.QGroupBox(self.centralwidget)
        self.plotGroup.setMinimumSize(QtCore.QSize(0, 100))
        self.plotGroup.setObjectName("plotGroup")
        self.radioButton_time = QtGui.QRadioButton(self.plotGroup)
        self.radioButton_time.setGeometry(QtCore.QRect(0, 30, 116, 22))
        self.radioButton_time.setChecked(True)
        self.radioButton_time.setObjectName("radioButton_time")
        self.radioButton_range = QtGui.QRadioButton(self.plotGroup)
        self.radioButton_range.setGeometry(QtCore.QRect(0, 50, 116, 22))
        self.radioButton_range.setObjectName("radioButton_range")
        self.radioButton_none = QtGui.QRadioButton(self.plotGroup)
        self.radioButton_none.setGeometry(QtCore.QRect(0, 70, 116, 22))
        self.radioButton_none.setObjectName("radioButton_none")
        self.gridLayout.addWidget(self.plotGroup, 7, 1, 1, 1)
        self.logBox = QtGui.QCheckBox(self.centralwidget)
        self.logBox.setObjectName("logBox")
        self.gridLayout.addWidget(self.logBox, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRadar = QtGui.QMenu(self.menubar)
        self.menuRadar.setObjectName("menuRadar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDetect_radars = QtGui.QAction(MainWindow)
        self.actionDetect_radars.setObjectName("actionDetect_radars")
        self.actionSet_log_file = QtGui.QAction(MainWindow)
        self.actionSet_log_file.setObjectName("actionSet_log_file")
        self.menuFile.addAction(self.actionSet_log_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRadar.addAction(self.actionDetect_radars)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRadar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Triggering", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTrigCont.setText(QtGui.QApplication.translate("MainWindow", "Continous", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTrigSingle.setText(QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Big Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bigrange.setText(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bigwaterfall.setText(QtGui.QApplication.translate("MainWindow", "Waterfall", None, QtGui.QApplication.UnicodeUTF8))
        self.rfpowerBox.setText(QtGui.QApplication.translate("MainWindow", "RF power", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTrigger.setText(QtGui.QApplication.translate("MainWindow", "Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.plotGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Small Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_time.setText(QtGui.QApplication.translate("MainWindow", "Ti&me", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_range.setText(QtGui.QApplication.translate("MainWindow", "Fre&quency", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_none.setText(QtGui.QApplication.translate("MainWindow", "&None", None, QtGui.QApplication.UnicodeUTF8))
        self.logBox.setText(QtGui.QApplication.translate("MainWindow", "Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRadar.setTitle(QtGui.QApplication.translate("MainWindow", "&Radar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDetect_radars.setText(QtGui.QApplication.translate("MainWindow", "&Detect radars", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_log_file.setText(QtGui.QApplication.translate("MainWindow", "Set log file", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
